// Extracts the ABIs the frontend needs straight out of the Foundry build, so the
// app can never drift from the contracts. Run automatically before dev/build.
//
// Requires `forge build` to have been run in the repo root first.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "..", "out");

/** @type {Array<[string, string, string]>} name, artifact dir, contract file */
const WANTED = [
  ["launchpadAbi", "UnderwaterLaunchpad.sol", "UnderwaterLaunchpad.json"],
  ["memeTokenAbi", "MemeToken.sol", "MemeToken.json"],
  ["routerAbi", "UnderwaterRouter.sol", "UnderwaterRouter.json"],
  ["factoryAbi", "UnderwaterFactory.sol", "UnderwaterFactory.json"],
  ["pairAbi", "UnderwaterPair.sol", "UnderwaterPair.json"],
];

let body = `// GENERATED by scripts/abis.mjs from the Foundry build. Do not edit.\n`;

for (const [name, dir, file] of WANTED) {
  const path = join(out, dir, file);
  let artifact;
  try {
    artifact = JSON.parse(readFileSync(path, "utf8"));
  } catch {
    console.error(
      `\n  Missing ${path}\n  Run \`forge build\` in the repo root first.\n`,
    );
    process.exit(1);
  }
  body += `\nexport const ${name} = ${JSON.stringify(artifact.abi)} as const;\n`;
}

mkdirSync(join(here, "..", "lib"), { recursive: true });
writeFileSync(join(here, "..", "lib", "abis.ts"), body);
console.log(`abis.ts written (${WANTED.length} contracts)`);
