// Extracts the ABIs the frontend needs straight out of the Foundry build, so the
// app can never drift from the contracts. Run automatically before dev/build.
//
// Requires `forge build` to have been run in the repo root first.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "..", "out");

/** @type {Array<[string, string, string]>} name, artifact dir, contract file */
const WANTED = [
  ["launchpadAbi", "UnderwaterLaunchpad.sol", "UnderwaterLaunchpad.json"],
  ["memeTokenAbi", "MemeToken.sol", "MemeToken.json"],
  ["routerAbi", "UnderwaterRouter.sol", "UnderwaterRouter.json"],
  ["factoryAbi", "UnderwaterFactory.sol", "UnderwaterFactory.json"],
  ["pairAbi", "UnderwaterPair.sol", "UnderwaterPair.json"],
  // The NFT collection. Independent of the launchpad — it is what /mint reads.
  ["platesAbi", "UnderwaterPlates.sol", "UnderwaterPlates.json"],
  // Allowlist intake, a separate deploy again: it opens and closes before the
  // collection's own phases, and a chain can have one without the other.
  ["waitlistAbi", "UnderwaterWaitlist.sol", "UnderwaterWaitlist.json"],
  // The variant whose window the owner can move. Its registration and read
  // surface is a superset of the one above, so `waitlistAbi` drives every page
  // either way and this is imported only for the two functions that are new:
  // `owner`, which is how a page tells the two apart on chain, and `setWindow`.
  [
    "waitlistFlexibleAbi",
    "UnderwaterWaitlistFlexible.sol",
    "UnderwaterWaitlistFlexible.json",
  ],
  // The uwPoint rate card and coupon book. Another independent deploy, and the
  // one that can arrive last: balances are counted off chain from logs the
  // contracts above already emit, so this only holds the numbers those counts are
  // multiplied by. A chain can have every contract above and no points contract,
  // which is the state a chain is in before this is deployed to it.
  ["pointsAbi", "UnderwaterPoints.sol", "UnderwaterPoints.json"],
];

let body = `// GENERATED by scripts/abis.mjs from the Foundry build. Do not edit.\n`;

for (const [name, dir, file] of WANTED) {
  const path = join(out, dir, file);
  let artifact;
  try {
    artifact = JSON.parse(readFileSync(path, "utf8"));
  } catch {
    console.error(
      `\n  Missing ${path}\n  Run \`forge build\` in the repo root first.\n`,
    );
    process.exit(1);
  }
  body += `\nexport const ${name} = ${JSON.stringify(artifact.abi)} as const;\n`;
}

mkdirSync(join(here, "..", "lib"), { recursive: true });
writeFileSync(join(here, "..", "lib", "abis.ts"), body);
console.log(`abis.ts written (${WANTED.length} contracts)`);
