// Extracts the ABIs the indexer needs straight out of the Foundry build, so the
// indexer can never drift from the contracts. Run automatically before dev/start.
//
// The same script the frontend has (web/scripts/abis.mjs), pointed at a different
// output file and asking for fewer contracts — deliberately a copy rather than a
// shared module, because the two packages have no workspace between them and a
// build step that reaches into a sibling's scripts directory is worse than fifty
// duplicated lines.
//
// Requires `forge build` to have been run in the repo root first.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "..", "out");

/** @type {Array<[string, string, string]>} name, artifact dir, contract file */
const WANTED = [
  // The launchpad, which is both the curve and — via `Graduated` — the registry of
  // every pair worth indexing. See ponder.config.ts for why that replaces the DEX
  // factory here.
  ["launchpadAbi", "UnderwaterLaunchpad.sol", "UnderwaterLaunchpad.json"],
  // The pair, for `Swap`, `Sync`, and the one `token0` read per graduation.
  ["pairAbi", "UnderwaterPair.sol", "UnderwaterPair.json"],
];

let body = `// GENERATED by scripts/abis.mjs from the Foundry build. Do not edit.\n`;

for (const [name, dir, file] of WANTED) {
  const path = join(out, dir, file);
  let artifact;
  try {
    artifact = JSON.parse(readFileSync(path, "utf8"));
  } catch {
    console.error(
      `\n  Missing ${path}\n  Run \`forge build\` in the repo root first.\n`,
    );
    process.exit(1);
  }
  body += `\nexport const ${name} = ${JSON.stringify(artifact.abi)} as const;\n`;
}

mkdirSync(join(here, "..", "abis"), { recursive: true });
writeFileSync(join(here, "..", "abis", "generated.ts"), body);
console.log(`abis/generated.ts written (${WANTED.length} contracts)`);
