// Extracts the ABIs the indexer needs straight out of the Foundry build, so the
// indexer can never drift from the contracts. Run automatically before dev/start.
//
// The same script the frontend has (web/scripts/abis.mjs), pointed at a different
// output file and asking for fewer contracts — deliberately a copy rather than a
// shared module, because the two packages have no workspace between them and a
// build step that reaches into a sibling's scripts directory is worse than fifty
// duplicated lines.
//
// Prefers `forge build` output, and falls back to the committed `abis/generated.ts`
// when there is none. That fallback is what makes the indexer deployable: `out/` is
// gitignored, so a container built from a clone has no Foundry and no artifacts, and
// exiting non-zero there would mean `npm start` could never run on a host. Locally,
// where `out/` does exist, the file is always regenerated — so the committed copy
// cannot quietly go stale while someone is editing contracts.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "..", "out");
const target = join(here, "..", "abis", "generated.ts");

/** @type {Array<[string, string, string]>} name, artifact dir, contract file */
const WANTED = [
  // The launchpad, which is both the curve and — via `Graduated` — the registry of
  // every pair worth indexing. See ponder.config.ts for why that replaces the DEX
  // factory here.
  ["launchpadAbi", "UnderwaterLaunchpad.sol", "UnderwaterLaunchpad.json"],
  // The pair, for `Swap`, `Sync`, and the one `token0` read per graduation.
  ["pairAbi", "UnderwaterPair.sol", "UnderwaterPair.json"],
  // The waitlist, for `Registered` — which carries a registration and a referral
  // attribution in one log, and so is half the uwPoints inputs on its own.
  ["waitlistAbi", "UnderwaterWaitlist.sol", "UnderwaterWaitlist.json"],
  // The points contract, for `Redeemed` and `Granted`. Not for the rate card: rates
  // are read from the chain at request time, because a balance is priced on read and
  // an indexed copy would be a second answer to a question with one.
  ["pointsAbi", "UnderwaterPoints.sol", "UnderwaterPoints.json"],
];

let body = `// GENERATED by scripts/abis.mjs from the Foundry build. Do not edit.\n`;

for (const [name, dir, file] of WANTED) {
  const path = join(out, dir, file);
  let artifact;
  try {
    artifact = JSON.parse(readFileSync(path, "utf8"));
  } catch {
    if (existsSync(target)) {
      console.log(`no Foundry build at ${out} — keeping the committed abis/generated.ts`);
      process.exit(0);
    }
    console.error(
      `\n  Missing ${path}, and no abis/generated.ts to fall back on.` +
        `\n  Run \`forge build\` in the repo root first.\n`,
    );
    process.exit(1);
  }
  body += `\nexport const ${name} = ${JSON.stringify(artifact.abi)} as const;\n`;
}

mkdirSync(join(here, "..", "abis"), { recursive: true });
writeFileSync(target, body);
console.log(`abis/generated.ts written (${WANTED.length} contracts)`);
