// Copies the curve maths out of the web app, so `indexer/` is a directory a host can
// build on its own.
//
// `src/curve.ts` used to import `../../web/lib/curve` directly, which is fine on a
// developer's checkout and impossible on a platform: Railway and Render build a
// service from one subdirectory, and nothing above it exists. Vendoring it here keeps
// the deploy honest without giving up the single source of truth — the copy is
// generated, never edited, and regenerated on every local dev/start, so an edit to
// `web/lib/curve.ts` lands here the next time anybody runs the indexer.
//
// Same bargain as scripts/abis.mjs, for the same reason: prefer the real source, keep
// the committed copy when the source is out of reach, and fail loudly only when there
// is neither. `web/lib/curve.ts` has no imports of its own, which is what makes a byte
// copy a legitimate module rather than the first half of one.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const source = join(here, "..", "..", "web", "lib", "curve.ts");
const target = join(here, "..", "vendor", "curve.ts");

let body;
try {
  body = readFileSync(source, "utf8");
} catch {
  if (existsSync(target)) {
    console.log("no web/lib/curve.ts — keeping the committed vendor/curve.ts");
    process.exit(0);
  }
  console.error(
    `\n  Missing ${source}, and no vendor/curve.ts to fall back on.` +
      `\n  This has to run from a checkout that includes the web app.\n`,
  );
  process.exit(1);
}

// An import in the source would be a broken import here, since only this one file is
// copied. Catching it now beats a module-resolution error inside Ponder's build.
const imports = body.match(/^\s*import\s.+$/gm);
if (imports) {
  console.error(
    `\n  web/lib/curve.ts has grown imports, so it can no longer be vendored as one file:\n` +
      imports.map((line) => `    ${line.trim()}`).join("\n") +
      `\n\n  Either keep it self-contained or vendor its dependencies too.\n`,
  );
  process.exit(1);
}

const header =
  `// GENERATED by scripts/curve.mjs from web/lib/curve.ts. Do not edit.\n` +
  `//\n` +
  `// Committed on purpose: a deployed indexer builds from this directory alone and has\n` +
  `// no web/ to read. Edit the original.\n\n`;

mkdirSync(join(here, "..", "vendor"), { recursive: true });
writeFileSync(target, header + body);
console.log(`vendor/curve.ts written from web/lib/curve.ts`);
