// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

/// @title MerkleProof
/// @notice Inclusion proofs against a Merkle root, for the allowlist.
///
/// @dev Written here rather than pulled in, like every other util in this repo:
///      nothing in the trust path should come from a submodule.
///
///      **Sorted pairs.** Each step hashes the two nodes in ascending order, so a
///      proof carries only the sibling hashes and no left/right flags. That is
///      what `merkletreejs` with `sortPairs: true` and OpenZeppelin's own
///      verifier both produce, so a root generated by the standard off-chain
///      tooling verifies here without translation. The cost is that the tree
///      cannot distinguish a left sibling from a right one, which is fine for
///      proving membership and is the reason leaves are hashed twice below.
///
///      **Leaves must be double-hashed by the caller.** In a binary tree whose
///      internal nodes are `keccak256(a, b)`, a 64-byte "leaf" could otherwise be
///      presented as a pair of real nodes and verify — the classic
///      second-preimage attack. Hashing the leaf twice makes leaf digests
///      unforgeable as internal nodes, because an internal node is never the hash
///      of a single 32-byte word. `UnderwaterPlates._leaf` is the only caller and
///      does exactly that.
library MerkleProof {
    /// @notice True if `leaf` is in the tree with root `root`.
    /// @dev `calldata` rather than `memory`: the proof comes straight off the
    ///      transaction and copying it would cost gas for nothing. An empty proof
    ///      is meaningful — it proves a single-leaf tree where the leaf *is* the
    ///      root — so it is not rejected here. Callers that must never accept a
    ///      zero root are the ones that check it, since `verify` against a zero
    ///      root is how an unset allowlist would let everybody in.
    function verify(bytes32[] calldata proof, bytes32 root, bytes32 leaf) internal pure returns (bool) {
        bytes32 computed = leaf;

        for (uint256 i; i < proof.length; ++i) {
            bytes32 sibling = proof[i];
            computed = computed < sibling
                ? keccak256(abi.encodePacked(computed, sibling))
                : keccak256(abi.encodePacked(sibling, computed));
        }

        return computed == root;
    }
}
