// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

/// @title UnderwaterScenes
/// @notice The backdrop and the umbilical.
///         The backdrop is plate space. The tether is drawn as pure offsets from the diver's
///         head, so it too comes back translated onto the diver it belongs to.
///
/// @dev GENERATED by `python art/solidify.py` from art/traits/**. Do not edit by
///      hand — regenerate. The markup is byte-for-byte what art/render.py
///      composes off chain, which is what lets the two be diffed against each
///      other instead of eyeballed.
///
///      Stateless, ownerless, immutable: there is nothing to configure and
///      nothing to trust here beyond the bytes, which anyone can read back with
///      `eth_getCode` and compare against this file.
contract UnderwaterScenes {
    error BadIndex();

    /// @notice Every asset this contract holds, for one plate, ready to compose.
    /// @dev Batched because the renderer always needs all of them, and one
    ///      staticcall returning 2 strings beats 2 calls returning one.

    ///      Takes the diver index as well as its own, because what it returns is
    ///      positioned against that diver and a caller has no business doing that
    ///      arithmetic itself.
    /// @return backdrop The backdrop, in plate space.
    /// @return umbilical The umbilical, translated onto this diver's helmet.
    function parts(uint256 scene, uint256 tether, uint256 diver)
        external
        pure
        returns (string memory backdrop, string memory umbilical)
    {
        backdrop = _scene(scene);

        // Unconditional, unlike the other wrappers: every tether option draws
        // something, so there is no blank case to skip and no reason to pay for
        // the check.
        umbilical = string.concat(_tetherAnchor(diver), _tether(tether), "</g>");
    }

    /// @dev Where the umbilical leaves the helmet, as the group that puts it there. Generated from the
    ///      manifest's anchor table, so the six transforms cannot drift from the
    ///      ones art/render.py composes.
    function _tetherAnchor(uint256 diver) private pure returns (string memory) {
        if (diver == 0) return '<g transform="translate(232 106)">'; // human
        if (diver == 1) return '<g transform="translate(232 88)">'; // skeleton
        if (diver == 2) return '<g transform="translate(232 128)">'; // cephalopod
        if (diver == 3) return '<g transform="translate(232 132)">'; // jellyfish
        if (diver == 4) return '<g transform="translate(208 234)">'; // angler
        if (diver == 5) return '<g transform="translate(232 168)">'; // drone
        revert BadIndex();
    }

    /// @dev Scene, 5 options, index order fixed by the
    ///      trait table. Reverts on an out-of-range index rather than drawing
    ///      nothing, because a silent blank would look like valid art.
    function _scene(uint256 i) private pure returns (string memory) {
        if (i == 0) return ""; // openWater
        if (i == 1) {
            // wreck
            return '<g opacity=".34"><path d="M-20 566 Q80 476 220 492 L358 504 Q400 510 410 544 L410 620 L-'
                '20 620 Z" class="fill"/><path d="M60 504 L52 430 M118 496 L112 418 M178 492 L174 442" cl'
                'ass="st" stroke-width="7"/><path d="M44 540 h300" class="paperst" stroke-width="4"/><pat'
                'h d="M240 512 q30 -14 60 2" class="paperst" stroke-width="4"/></g>';
        }
        if (i == 2) {
            // kelp
            return '<g opacity=".3"><path d="M40 620 Q24 500 52 400 Q72 320 48 240" class="st" stroke-width='
                '"8"/><path d="M96 620 Q112 494 84 396 Q64 316 92 236" class="st" stroke-width="6"/><path'
                ' d="M330 620 Q348 490 320 388 Q300 306 328 228" class="st" stroke-width="8"/><path d="M3'
                '68 620 Q352 512 376 420" class="st" stroke-width="6"/><path d="M52 400 q28 -22 46 -6 M84'
                " 396 q-28 -24 -48 -8 M320 388 q28 -22 48 -6 M48 240 q26 -20 44 -4 M328 228 q-26 -20 -46 "
                '-4" class="st" stroke-width="5"/></g>';
        }
        if (i == 3) {
            // vent
            return '<g opacity=".32"><path d="M130 620 L162 470 Q176 440 196 470 L228 620 Z" class="fill"/><'
                'circle cx="180" cy="418" r="26" class="st" stroke-width="5"/><circle cx="200" cy="352" r'
                '="34" class="st" stroke-width="4"/><circle cx="176" cy="278" r="42" class="st" stroke-wi'
                'dth="4"/><circle cx="206" cy="196" r="50" class="st" stroke-width="3"/><circle cx="184" '
                'cy="110" r="58" class="st" stroke-width="3"/></g>';
        }
        if (i == 4) {
            // chainCurtain
            return '<g opacity=".26"><path d="M56 -10 V420" class="st" stroke-width="13" stroke-dasharray="1'
                '5 11"/><path d="M148 -10 V300" class="st" stroke-width="11" stroke-dasharray="13 10"/><p'
                'ath d="M262 -10 V486" class="st" stroke-width="13" stroke-dasharray="15 11"/><path d="M3'
                '52 -10 V356" class="st" stroke-width="10" stroke-dasharray="12 9"/></g>';
        }
        revert BadIndex();
    }

    /// @dev Tether, 4 options, index order fixed by the
    ///      trait table. Reverts on an out-of-range index rather than drawing
    ///      nothing, because a silent blank would look like valid art.
    function _tether(uint256 i) private pure returns (string memory) {
        if (i == 0) {
            // intact
            return '<path d="M0 0 Q90 -62 64 -178" class="st" stroke-width="6"/>';
        }
        if (i == 1) {
            // frayed
            return
                '<path d="M0 0 Q90 -62 64 -178" class="st" stroke-width="6" stroke-dasharray="26 7 12 5"/' ">";
        }
        if (i == 2) {
            // severed
            return '<path d="M0 0 Q36 -30 46 -68" class="st" stroke-width="6"/><path d="M54 -96 Q64 -138 60 '
                '-178" class="st" stroke-width="6" opacity=".45"/>';
        }
        if (i == 3) {
            // chain
            return '<path d="M0 0 Q90 -62 64 -178" class="st" stroke-width="11" stroke-dasharray="13 9" stro'
                'ke-linecap="butt"/>';
        }
        revert BadIndex();
    }
}
