// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

/// @title UnderwaterFigures
/// @notice The figure, and what it wears and carries — already planted on it.
///         The body is drawn in plate space. The headgear and the held item are unit sketches,
///         which mean nothing until they are scaled onto a particular diver, so this contract
///         wraps them in that diver's own anchor group before returning them.
///
/// @dev GENERATED by `python art/solidify.py` from art/traits/**. Do not edit by
///      hand — regenerate. The markup is byte-for-byte what art/render.py
///      composes off chain, which is what lets the two be diffed against each
///      other instead of eyeballed.
///
///      Stateless, ownerless, immutable: there is nothing to configure and
///      nothing to trust here beyond the bytes, which anyone can read back with
///      `eth_getCode` and compare against this file.
contract UnderwaterFigures {
    error BadIndex();

    /// @notice Every asset this contract holds, for one plate, ready to compose.
    /// @dev Batched because the renderer always needs all of them, and one
    ///      staticcall returning 3 strings beats 3 calls returning one.

    ///      Takes the diver index as well as its own, because what it returns is
    ///      positioned against that diver and a caller has no business doing that
    ///      arithmetic itself.
    /// @return body The diver, in plate space.
    /// @return worn The headgear, anchored to this diver's head, or "" if bare.
    /// @return carried The held item, anchored and rotated to this diver's hand, or "" if empty-handed.
    function parts(uint256 diver, uint256 headgear, uint256 held)
        external
        pure
        returns (string memory body, string memory worn, string memory carried)
    {
        body = _diver(diver);

        string memory sketch = _headgear(headgear);
        if (bytes(sketch).length != 0) worn = string.concat(_headAnchor(diver), sketch, "</g>");

        sketch = _held(held);
        if (bytes(sketch).length != 0) carried = string.concat(_handAnchor(diver), sketch, "</g>");
    }

    /// @dev Where a headgear sits on each diver, as the group that puts it there. Generated from the
    ///      manifest's anchor table, so the six transforms cannot drift from the
    ///      ones art/render.py composes.
    function _headAnchor(uint256 diver) private pure returns (string memory) {
        if (diver == 0) return '<g transform="translate(200 130) scale(42)">'; // human
        if (diver == 1) return '<g transform="translate(200 112) scale(44)">'; // skeleton
        if (diver == 2) return '<g transform="translate(200 152) scale(54)">'; // cephalopod
        if (diver == 3) return '<g transform="translate(200 156) scale(62)">'; // jellyfish
        if (diver == 4) return '<g transform="translate(176 258) scale(48)">'; // angler
        if (diver == 5) return '<g transform="translate(200 192) scale(42)">'; // drone
        revert BadIndex();
    }

    /// @dev Where a held item sits, and at what angle, as the group that puts it there. Generated from the
    ///      manifest's anchor table, so the six transforms cannot drift from the
    ///      ones art/render.py composes.
    function _handAnchor(uint256 diver) private pure returns (string memory) {
        if (diver == 0) return '<g transform="translate(300 358) rotate(-14) scale(44)">'; // human
        if (diver == 1) return '<g transform="translate(282 300) rotate(-6) scale(44)">'; // skeleton
        if (diver == 2) return '<g transform="translate(300 438) rotate(14) scale(44)">'; // cephalopod
        if (diver == 3) return '<g transform="translate(236 450) rotate(4) scale(44)">'; // jellyfish
        if (diver == 4) return '<g transform="translate(216 452) rotate(0) scale(44)">'; // angler
        if (diver == 5) return '<g transform="translate(312 394) rotate(22) scale(44)">'; // drone
        revert BadIndex();
    }

    /// @dev Diver, 6 options, index order fixed by the
    ///      trait table. Reverts on an out-of-range index rather than drawing
    ///      nothing, because a silent blank would look like valid art.
    function _diver(uint256 i) private pure returns (string memory) {
        if (i == 0) {
            // human
            return '<circle cx="200" cy="130" r="31" class="fill"/><path d="M188 158 h24 v16 h-24 z" class="'
                'fill"/><path d="M124 176 Q200 200 276 176 L286 212 Q200 242 114 212 Z" class="fill"/><pa'
                'th d="M126 212 Q140 330 152 400" class="st" stroke-width="7"/><path d="M274 212 Q260 330'
                ' 248 400" class="st" stroke-width="7"/><path d="M152 400 L248 400" class="st" stroke-wid'
                'th="7"/><path d="M144 310 Q200 326 256 310" class="st" stroke-width="9"/><path d="M126 2'
                '22 Q88 290 100 350" class="st" stroke-width="13"/><path d="M274 222 Q312 290 300 350" cl'
                'ass="st" stroke-width="13"/><circle cx="100" cy="358" r="12" class="fill"/><circle cx="3'
                '00" cy="358" r="12" class="fill"/><path d="M168 400 L158 514" class="st" stroke-width="1'
                '5"/><path d="M232 400 L242 514" class="st" stroke-width="15"/><path d="M136 516 h44 v25 '
                'h-50 z" class="fill"/><path d="M264 516 h-44 v25 h50 z" class="fill"/>';
        }
        if (i == 1) {
            // skeleton
            return '<path d="M164 118 Q164 74 200 74 Q236 74 236 118 Q236 146 224 158 L176 158 Q164 146 164 '
                '118 Z" class="fill"/><ellipse cx="184" cy="118" rx="11" ry="13" class="paperfill"/><elli'
                'pse cx="216" cy="118" rx="11" ry="13" class="paperfill"/><path d="M196 134 l4 10 l4 -10"'
                ' class="paperst" stroke-width="3"/><path d="M178 160 h44 v12 h-44 z" class="fill"/><path'
                ' d="M200 172 L200 356" class="st" stroke-width="9"/><path d="M200 196 Q152 206 142 246" '
                'class="st" stroke-width="6"/><path d="M200 196 Q248 206 258 246" class="st" stroke-width'
                '="6"/><path d="M200 220 Q156 232 148 268" class="st" stroke-width="6"/><path d="M200 220'
                ' Q244 232 252 268" class="st" stroke-width="6"/><path d="M200 244 Q162 256 156 288" clas'
                's="st" stroke-width="6"/><path d="M200 244 Q238 256 244 288" class="st" stroke-width="6"'
                '/><path d="M178 186 Q126 226 118 306" class="st" stroke-width="7"/><path d="M222 186 Q27'
                '4 226 282 300" class="st" stroke-width="7"/><path d="M158 356 Q200 380 242 356 L236 388 '
                'Q200 404 164 388 Z" class="fill"/><path d="M176 396 L164 510" class="st" stroke-width="9'
                '"/><path d="M224 396 L236 510" class="st" stroke-width="9"/><path d="M148 514 h36" class'
                '="st" stroke-width="9"/><path d="M216 514 h36" class="st" stroke-width="9"/>';
        }
        if (i == 2) {
            // cephalopod
            return '<path d="M200 84 Q262 84 262 178 Q262 232 200 240 Q138 232 138 178 Q138 84 200 84 Z" cla'
                'ss="fill"/><circle cx="174" cy="176" r="16" class="paperfill"/><circle cx="226" cy="176"'
                ' r="16" class="paperfill"/><path d="M166 176 h16" class="st" stroke-width="6"/><path d="'
                'M218 176 h16" class="st" stroke-width="6"/><path d="M158 236 Q132 320 152 396 Q166 444 1'
                '38 470" class="st" stroke-width="12"/><path d="M180 240 Q168 336 186 420 Q196 470 176 50'
                '2" class="st" stroke-width="12"/><path d="M200 242 Q200 350 212 436 Q220 486 246 508" cl'
                'ass="st" stroke-width="12"/><path d="M220 240 Q244 330 240 408 Q238 452 272 476" class="'
                'st" stroke-width="12"/><path d="M242 236 Q276 312 272 372 Q268 414 300 436" class="st" s'
                'troke-width="12"/><path d="M148 232 Q104 288 108 348 Q110 388 82 402" class="st" stroke-'
                'width="10"/><circle cx="138" cy="474" r="6" class="fill"/>';
        }
        if (i == 3) {
            // jellyfish
            return '<path d="M112 202 Q112 100 200 100 Q288 100 288 202 Q244 224 200 224 Q156 224 112 202 Z"'
                ' class="fill"/><path d="M112 202 q22 22 44 0 q22 22 44 0 q22 22 44 0 q22 22 44 0" class='
                '"st" stroke-width="7"/><path d="M148 128 Q152 178 142 202" class="paperst" stroke-width='
                '"4"/><path d="M200 112 Q200 170 200 214" class="paperst" stroke-width="4"/><path d="M252'
                ' 128 Q248 178 258 202" class="paperst" stroke-width="4"/><path d="M164 220 Q158 300 176 '
                '356 Q190 400 170 452" class="st" stroke-width="9"/><path d="M188 224 Q182 320 196 392 Q2'
                '06 440 196 496" class="st" stroke-width="9"/><path d="M212 224 Q222 320 210 392 Q204 424'
                ' 236 448" class="st" stroke-width="9"/><path d="M236 220 Q246 300 228 356 Q214 400 236 4'
                '56" class="st" stroke-width="9"/><path d="M134 210 Q108 288 126 344" class="st" stroke-w'
                'idth="5"/><path d="M266 210 Q292 288 274 344" class="st" stroke-width="5"/>';
        }
        if (i == 4) {
            // angler
            return '<path d="M116 296 Q140 200 226 198 Q290 198 306 268 Q316 312 290 350 Q248 388 180 372 Q1'
                '30 356 116 296 Z" class="fill"/><circle cx="176" cy="266" r="15" class="paperfill"/><cir'
                'cle cx="180" cy="266" r="6" class="fill"/><path d="M124 316 Q176 352 250 340 Q288 332 30'
                '2 306" class="paperst" stroke-width="5"/><path d="M132 318 l12 20 l10 -18 l12 20 l10 -18'
                ' l12 20 l10 -18 l12 20 l10 -18 l12 18 l10 -16" class="paperst" stroke-width="4"/><path d'
                '="M226 200 Q216 132 174 108 Q146 92 132 104" class="st" stroke-width="9"/><circle cx="12'
                '6" cy="106" r="18" class="fill"/><circle cx="126" cy="106" r="8" class="paperfill"/><pat'
                'h d="M306 268 Q356 226 366 262 Q374 300 346 336 Q322 366 292 348" class="fill"/><path d='
                '"M196 372 Q192 424 216 452" class="st" stroke-width="8"/><path d="M254 366 Q266 414 250 '
                '446" class="st" stroke-width="8"/>';
        }
        if (i == 5) {
            // drone
            return '<path d="M132 208 h136 q10 0 10 10 v112 q0 10 -10 10 h-136 q-10 0 -10 -10 v-112 q0 -10 1'
                '0 -10 z" class="st" stroke-width="7"/><circle cx="200" cy="192" r="30" class="fill"/><ci'
                'rcle cx="200" cy="192" r="13" class="paperfill"/><path d="M126 236 h-26 a20 20 0 0 0 0 4'
                '0 h26" class="st" stroke-width="6"/><circle cx="100" cy="256" r="19" class="st" stroke-w'
                'idth="5"/><path d="M274 236 h26 a20 20 0 0 1 0 40 h-26" class="st" stroke-width="6"/><ci'
                'rcle cx="300" cy="256" r="19" class="st" stroke-width="5"/><path d="M278 306 Q322 318 32'
                '8 356 Q332 384 312 394" class="st" stroke-width="8"/><path d="M160 226 h34 M160 246 h50 '
                'M160 266 h28" class="paperst" stroke-width="4"/><path d="M150 340 v40 M250 340 v40" clas'
                's="st" stroke-width="7"/><path d="M124 380 h60 M216 380 h60" class="st" stroke-width="9"'
                "/>";
        }
        revert BadIndex();
    }

    /// @dev Headgear, 5 options, index order fixed by the
    ///      trait table. Reverts on an out-of-range index rather than drawing
    ///      nothing, because a silent blank would look like valid art.
    function _headgear(uint256 i) private pure returns (string memory) {
        if (i == 0) {
            // brass
            return '<path d="M-1 .05 A1 1 0 0 1 1 .05 L1 .62 Q0 .92 -1 .62 Z" class="fill"/><circle cy=".08"'
                ' r=".5" class="paperfill"/><circle cy=".08" r=".5" class="st" stroke-width=".08"/><path '
                'd="M0 -.42 V.58" class="st" stroke-width=".07"/><circle cx="-.78" cy=".2" r=".08" class='
                '"paperfill"/><circle cx=".78" cy=".2" r=".08" class="paperfill"/><path d="M-1.16 .62 Q0 '
                '1.0 1.16 .62 L1.22 1.02 Q0 1.42 -1.22 1.02 Z" class="fill"/>';
        }
        if (i == 1) {
            // scubaMask
            return '<path d="M-.88 -.32 Q0 -.54 .88 -.32 L.8 .34 Q0 .6 -.8 .34 Z" class="fill"/><path d="M-.'
                '7 -.24 Q0 -.42 .7 -.24 L.64 .2 Q0 .42 -.64 .2 Z" class="paperfill"/><path d="M-.88 -.12 '
                'H-1.34 M.88 -.12 H1.34" class="st" stroke-width=".11"/><path d="M.3 .5 Q.62 .92 .36 1.34'
                '" class="st" stroke-width=".13"/><circle cx=".36" cy="1.44" r=".16" class="fill"/>';
        }
        if (i == 2) {
            // sphere
            return '<circle r="1.78" class="st" stroke-width=".09"/><path d="M-1.74 .32 Q0 .88 1.74 .32" cla'
                'ss="st" stroke-width=".06"/><path d="M-1.2 -1.26 Q0 -.72 1.2 -1.26" class="st" stroke-wi'
                'dth=".05"/><circle r=".14" cy="1.72" class="fill"/>';
        }
        if (i == 3) return ""; // bare
        if (i == 4) {
            // salvageRig
            return '<path d="M-.92 .52 L-.72 -.5 H.72 L.92 .52 Z" class="st" stroke-width=".1"/><path d="M-.'
                '56 -.5 V-.92 H.56 V-.5" class="st" stroke-width=".09"/><circle cy="-1.12" r=".22" class='
                '"fill"/><path d="M.56 -.92 L.92 -1.72" class="st" stroke-width=".07"/><circle cx=".96" c'
                'y="-1.8" r=".1" class="fill"/><path d="M-.4 .12 H.4" class="paperst" stroke-width=".09"/' ">";
        }
        revert BadIndex();
    }

    /// @dev Held, 6 options, index order fixed by the
    ///      trait table. Reverts on an out-of-range index rather than drawing
    ///      nothing, because a silent blank would look like valid art.
    function _held(uint256 i) private pure returns (string memory) {
        if (i == 0) {
            // harpoon
            return '<path d="M-.1 -2.0 L-.1 1.7" class="st" stroke-width=".14"/><path d="M-.1 -2.0 l-.3 .52 '
                'l.3 -.17 l.3 .17 z" class="fill"/><path d="M-.4 -1.4 l.3 .3 l.3 -.3" class="st" stroke-w'
                'idth=".1"/><path d="M-.46 .5 h.72" class="st" stroke-width=".12"/>';
        }
        if (i == 1) {
            // lantern
            return '<path d="M0 -.1 V.5" class="st" stroke-width=".1"/><path d="M-.44 .5 h.88 v.88 h-.88 z" '
                'class="fill"/><path d="M-.27 .65 h.54 v.58 h-.54 z" class="paperfill"/><circle cy=".94" '
                'r=".52" class="st" stroke-width=".05"/><circle cy=".94" r=".8" class="st" stroke-width="'
                '.04"/>';
        }
        if (i == 2) {
            // salvageBag
            return '<path d="M-.1 0 V.34" class="st" stroke-width=".09"/><path d="M-.52 .34 Q-.74 1.12 -.3 1'
                '.44 Q.12 1.68 .48 1.38 Q.8 1.04 .52 .34 Z" class="fill"/><path d="M-.52 .34 Q0 .5 .52 .3'
                '4" class="paperst" stroke-width=".1"/><path d="M-.2 .8 Q0 1.0 .24 .84" class="paperst" s'
                'troke-width=".07"/>';
        }
        if (i == 3) {
            // diveSlate
            return '<path d="M-.06 -.06 V.24" class="st" stroke-width=".08"/><path d="M-.54 .24 h1.08 v.9 h-'
                '1.08 z" class="fill"/><path d="M-.38 .44 h.6 M-.38 .62 h.74 M-.38 .8 h.44 M-.38 .96 h.66'
                '" class="paperst" stroke-width=".07"/>';
        }
        if (i == 4) {
            // cutHose
            return '<path d="M-.05 0 Q.42 .5 .3 1.12" class="st" stroke-width=".17"/><path d="M.3 1.12 l-.18'
                ' .26 m.18 -.26 l.2 .22 m-.2 -.22 l.02 .32" class="st" stroke-width=".07"/>';
        }
        if (i == 5) return ""; // empty
        revert BadIndex();
    }
}
