// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

/// @title UnderwaterMarks
/// @notice The relic in its specimen card, and the underwriter's stamp.
///         Both unit-space, both returned already framed. The card comes back in two halves
///         because the renderer has to drop four encrustation barnacles into the gap, drawn off
///         the plate's own PRNG stream — which this contract has no access to and should not.
///
/// @dev GENERATED by `python art/solidify.py` from art/traits/**. Do not edit by
///      hand — regenerate. The markup is byte-for-byte what art/render.py
///      composes off chain, which is what lets the two be diffed against each
///      other instead of eyeballed.
///
///      Stateless, ownerless, immutable: there is nothing to configure and
///      nothing to trust here beyond the bytes, which anyone can read back with
///      `eth_getCode` and compare against this file.
contract UnderwaterMarks {
    error BadIndex();

    /// @dev The chrome around the marks, split where content goes into it.
    string private constant CARD_OPEN = '<g transform="translate(94 508) scale(46)"><path d="M-1.85 1.5 Q-1.7 .08 -.95 -.7 Q0 -1.'
        '55 .95 -.7 Q1.7 .08 1.85 1.5 Z" class="paperfill" opacity=".82"/> ';

    string private constant CARD_CLOSE = '<path d="M-1.66 .82 Q-.7 .5 0 .78 Q.76 1.06 1.66 .8 L1.66 1.5 H-1.66 Z" class="fill" opa'
        'city=".5"/><path d="M-1.66 .82 Q-.7 .5 0 .78 Q.76 1.06 1.66 .8" class="st" stroke-width='
        '".05" opacity=".6"/></g>';

    string private constant STAMP_OPEN = '<g transform="translate(330 106) rotate(-7)" opacity=".55"><circle r="30" class="st" str'
        'oke-width="2.4"/><circle r="25.5" class="st" stroke-width=".9"/><g transform="scale(19)"' ">";

    string private constant STAMP_CLOSE = "</g></g>";

    /// @notice Every asset this contract holds, for one plate, ready to compose.
    /// @dev Batched because the renderer always needs all of them, and one
    ///      staticcall returning 3 strings beats 3 calls returning one.
    /// @return card The specimen card up to the point the encrustation goes, or "" if there is no relic.
    /// @return cardClose The rest of the card, to close after it.
    /// @return stamp The emblem in the underwriter's stamp, or "" if unstamped.
    function parts(uint256 relic, uint256 emblem)
        external
        pure
        returns (string memory card, string memory cardClose, string memory stamp)
    {
        string memory specimen = _relic(relic);
        if (bytes(specimen).length != 0) {
            card = string.concat(CARD_OPEN, specimen);
            cardClose = CARD_CLOSE;
        }

        string memory mark = _emblem(emblem);
        if (bytes(mark).length != 0) stamp = string.concat(STAMP_OPEN, mark, STAMP_CLOSE);
    }

    /// @dev Relic, 15 options, index order fixed by the
    ///      trait table. Reverts on an out-of-range index rather than drawing
    ///      nothing, because a silent blank would look like valid art.
    function _relic(uint256 i) private pure returns (string memory) {
        if (i == 0) return ""; // none
        if (i == 1) {
            // quill
            return '<path d="M.52 -1.0 Q-.28 -.2 -.6 .88" class="st" stroke-width=".1"/><path d="M.52 -1.0 Q'
                '.1 -.9 -.18 -.42 Q.12 -.5 .36 -.72 Z" class="fill"/><path d="M-.18 -.42 Q-.42 .06 -.5 .5'
                ' Q-.16 .18 .02 -.2 Z" class="fill"/><path d="M-.6 .88 l.18 .22" class="st" stroke-width='
                '".09"/>';
        }
        if (i == 2) {
            // tulip
            return '<path d="M.02 .92 Q-.04 .2 -.1 -.1" class="st" stroke-width=".12"/><path d="M-.44 -.12 Q'
                '-.5 -.72 -.2 -.94 Q-.1 -.5 0 -.92 Q.1 -.5 .2 -.94 Q.5 -.72 .44 -.12 Q0 .12 -.44 -.12 Z" '
                'class="fill"/><path d="M-.08 .34 Q-.6 .24 -.72 .66" class="st" stroke-width=".11"/>';
        }
        if (i == 3) {
            // hourglass
            return '<path d="M-.6 -.8 H.6 L.1 0 L.6 .8 H-.6 L-.1 0 Z" class="fill"/><path d="M-.72 -.88 h1.4'
                '4 M-.72 .88 h1.44" class="st" stroke-width=".13"/><path d="M-.28 .5 Q0 .34 .28 .5" class'
                '="paperst" stroke-width=".08"/>';
        }
        if (i == 4) {
            // ingots
            return '<path d="M-.9 .3 L-.66 -.02 H.66 L.9 .3 Z" class="fill"/><path d="M-.62 -.06 L-.4 -.38 H'
                '.4 L.62 -.06 Z" class="fill"/><path d="M-.34 -.42 L-.16 -.72 H.16 L.34 -.42 Z" class="fi'
                'll"/><path d="M-.9 .3 v.22 h1.8 v-.22" class="st" stroke-width=".08"/>';
        }
        if (i == 5) {
            // tentacle
            return '<path d="M-.7 .82 Q-.92 .1 -.5 -.32 Q-.08 -.72 .32 -.4 Q.72 -.08 .5 .42 Q.4 .8 .1 .86" c'
                'lass="st" stroke-width=".22"/><circle cx="-.52" cy=".5" r=".1" class="fill"/><circle cx='
                '"-.64" cy=".16" r=".09" class="fill"/><circle cx="-.4" cy="-.16" r=".09" class="fill"/><'
                'circle cx="-.04" cy="-.44" r=".08" class="fill"/>';
        }
        if (i == 6) {
            // frog
            return '<path d="M-1.02 .18 Q-1.06 -.44 -.6 -.68 Q0 -.9 .6 -.68 Q1.06 -.44 1.02 .18 Q.72 .62 0 .'
                '66 Q-.72 .62 -1.02 .18 Z" class="fill"/><circle cx="-.5" cy="-.62" r=".37" class="fill"/'
                '><circle cx=".5" cy="-.62" r=".37" class="fill"/><circle cx="-.5" cy="-.64" r=".27" clas'
                's="paperfill"/><circle cx=".5" cy="-.64" r=".27" class="paperfill"/><circle cx="-.4" cy='
                '"-.62" r=".11" class="fill"/><circle cx=".6" cy="-.62" r=".11" class="fill"/><path d="M-'
                '.88 .14 Q0 .44 .88 .10" class="paperst" stroke-width=".15"/><path d="M-.88 .14 Q0 .3 .88'
                ' .10" class="st" stroke-width=".05"/><path d="M-1.3 1.2 Q-1.16 .74 -.5 .58 M1.3 1.2 Q1.1'
                '6 .74 .5 .58" class="st" stroke-width=".17"/>';
        }
        if (i == 7) {
            // shiba
            return '<path d="M-.78 -.42 L-1.06 -1.02 L-.42 -.66 Q0 -.8 .42 -.66 L1.06 -1.02 L.78 -.42 Q.98 .'
                '02 .8 .34 Q.5 .74 0 .82 Q-.5 .74 -.8 .34 Q-.98 .02 -.78 -.42 Z" class="fill"/><path d="M'
                '-.64 -.3 Q-.38 -.46 -.14 -.28 M.16 -.28 Q.4 -.46 .66 -.3" class="paperst" stroke-width="'
                '.1"/><circle cx="-.34" cy="-.06" r=".14" class="paperfill"/><circle cx=".38" cy="-.06" r'
                '=".14" class="paperfill"/><circle cx="-.28" cy="-.05" r=".055" class="fill"/><circle cx='
                '".44" cy="-.05" r=".055" class="fill"/><path d="M-.44 .28 Q0 .1 .44 .28 Q.3 .74 0 .8 Q-.'
                '3 .74 -.44 .28 Z" class="paperfill" opacity=".92"/><path d="M-.13 .28 h.26 L0 .42 Z" cla'
                'ss="fill"/><path d="M0 .44 V.52 M-.17 .6 Q0 .68 .17 .58" class="st" stroke-width=".06"/>';
        }
        if (i == 8) {
            // magnifier
            return '<path d="M-.88 1.24 Q-.98 .2 -.5 -.34 Q-.06 -.84 .38 -.56 Q.9 -.24 .94 .5 Q.98 .96 .9 1.'
                '3 Z" class="fill"/><path d="M-.5 .1 Q-.32 -.38 .08 -.4 Q.44 -.34 .46 .1 Q.3 .48 -.06 .5 '
                'Q-.42 .44 -.5 .1 Z" class="paperfill" opacity=".13"/><path d="M-.44 -.14 Q-.08 -.44 .34 '
                '-.2" class="paperst" stroke-width=".07" opacity=".45"/><circle cx=".84" cy="-.62" r=".38'
                '" class="st" stroke-width=".11"/><circle cx=".84" cy="-.62" r=".28" class="paperfill" op'
                'acity=".35"/><path d="M.58 -.36 L.2 .02" class="st" stroke-width=".15"/>';
        }
        if (i == 9) {
            // visor
            return '<path d="M-.62 -.2 Q-.68 -.98 0 -1.02 Q.68 -.98 .62 -.2 Q.6 .2 .3 .32 L.3 .5 Q.92 .62 1.'
                '06 1.4 L-1.06 1.4 Q-.92 .62 -.3 .5 L-.3 .32 Q-.6 .2 -.62 -.2 Z" class="fill"/><path d="M'
                '-.58 -.4 h.42 v.28 h-.42 Z M.16 -.4 h.42 v.28 h-.42 Z" class="paperfill"/><path d="M-.16'
                ' -.3 h.32 M-.58 -.34 h-.08 M.58 -.34 h.08" class="paperst" stroke-width=".06"/><path d="'
                'M-.34 -.26 L-1.7 -.66 M.34 -.26 L1.7 -.66" class="st" stroke-width=".11"/><path d="M-.34'
                ' -.26 L-1.7 -.34 M.34 -.26 L1.7 -.34" class="st" stroke-width=".05" opacity=".5"/><path '
                'd="M0 .5 L-.26 1.1 M0 .5 L.26 1.1" class="paperst" stroke-width=".09"/>';
        }
        if (i == 10) {
            // skullCoin
            return '<circle r="1" class="fill"/><circle r=".82" class="paperfill"/><path d="M-.42 -.1 Q-.42 '
                "-.58 0 -.58 Q.42 -.58 .42 -.1 Q.42 .16 .28 .26 L.28 .44 H-.28 L-.28 .26 Q-.42 .16 -.42 -"
                '.1 Z" class="fill"/><circle cx="-.16" cy="-.2" r=".1" class="paperfill"/><circle cx=".16'
                '" cy="-.2" r=".1" class="paperfill"/><path d="M-.08 .02 h.16" class="paperst" stroke-wid'
                'th=".07"/>';
        }
        if (i == 11) {
            // coin
            return '<circle r="1" class="fill"/><circle r=".82" class="paperfill"/><path d="M-.3 -.5 H.12 a.'
                '25 .25 0 0 1 0 .48 H-.3 M-.3 -.02 H.2 a.26 .26 0 0 1 0 .52 H-.3 M-.3 -.56 V.56" class="s'
                't" stroke-width=".12"/><path d="M-.08 -.68 V-.5 M.14 -.68 V-.5 M-.08 .5 V.68 M.14 .5 V.6'
                '8" class="st" stroke-width=".09"/>';
        }
        if (i == 12) {
            // crystal
            return '<path d="M0 -1.05 L.6 -.06 L0 .3 L-.6 -.06 Z" class="fill"/><path d="M0 .44 L.6 .08 L0 1'
                '.05 L-.6 .08 Z" class="fill"/><path d="M0 -1.05 V.3 M-.6 -.06 L0 .3 L.6 -.06" class="pap'
                'erst" stroke-width=".07"/>';
        }
        if (i == 13) {
            // unicorn
            return '<path d="M-.5 .82 Q-.62 .1 -.3 -.2 L-.08 -.5 Q.12 -.78 .42 -.68 L.7 -.48 Q.8 -.26 .58 -.'
                '14 L.48 .02 Q.4 .5 .2 .82 Z" class="fill"/><path d="M.28 -.7 L.5 -1.32 L.62 -.6 Z" class'
                '="fill"/><circle cx=".34" cy="-.34" r=".1" class="paperfill"/><path d="M-.32 -.08 Q-.08 '
                '.12 .1 .32" class="paperst" stroke-width=".09"/>';
        }
        if (i == 14) {
            // medallion
            return '<circle r="1" class="st" stroke-width=".13"/><circle r=".82" class="fill"/><circle cy="-'
                '.28" r=".26" class="paperfill"/><path d="M-.4 .48 Q-.32 -.02 0 -.04 Q.32 -.02 .4 .48 Z" '
                'class="paperfill"/><path d="M-.44 .64 h.88" class="paperst" stroke-width=".09"/>';
        }
        revert BadIndex();
    }

    /// @dev Emblem, 8 options, index order fixed by the
    ///      trait table. Reverts on an out-of-range index rather than drawing
    ///      nothing, because a silent blank would look like valid art.
    function _emblem(uint256 i) private pure returns (string memory) {
        if (i == 0) return ""; // none
        if (i == 1) {
            // bitcoin
            return '<path d="M-.26 -.44 H.1 a.22 .22 0 0 1 0 .42 H-.26 M-.26 -.02 H.16 a.23 .23 0 0 1 0 .46 '
                'H-.26 M-.26 -.5 V.5" class="st" stroke-width=".14"/><path d="M-.06 -.64 V-.44 M.16 -.64 '
                'V-.44 M-.06 .44 V.64 M.16 .44 V.64" class="st" stroke-width=".11"/>';
        }
        if (i == 2) {
            // ethereum
            return '<path d="M0 -.76 L.44 -.02 L0 .22 Z" class="fill"/><path d="M0 -.76 L-.44 -.02 L0 .22 Z"'
                ' class="st" stroke-width=".07"/><path d="M0 .34 L.44 .06 L0 .78 Z" class="fill"/><path d'
                '="M0 .34 L-.44 .06 L0 .78 Z" class="st" stroke-width=".07"/>';
        }
        if (i == 3) {
            // kraken
            return '<path d="M-.44 -.1 Q-.5 -.74 0 -.78 Q.5 -.74 .44 -.1 Q.36 .16 0 .2 Q-.36 .16 -.44 -.1 Z"'
                ' class="fill"/><circle cx="-.2" cy="-.36" r=".1" class="paperfill"/><circle cx=".2" cy="'
                '-.36" r=".1" class="paperfill"/><path d="M-.34 .16 Q-.64 .5 -.5 .82 M-.12 .2 Q-.26 .58 -'
                '.1 .86 M.12 .2 Q.26 .58 .1 .86 M.34 .16 Q.64 .5 .5 .82" class="st" stroke-width=".11"/>';
        }
        if (i == 4) {
            // robinhood
            return '<path d="M0 -.82 V.74" class="st" stroke-width=".09"/><path d="M0 -.8 Q-.44 -.4 -.38 .1 '
                'Q-.12 -.2 0 -.5 Z" class="fill"/><path d="M0 -.8 Q.44 -.4 .38 .1 Q.12 -.2 0 -.5 Z" class'
                '="fill"/><path d="M0 -.3 Q-.36 .06 -.28 .5 Q-.08 .16 0 -.02 Z" class="fill"/><path d="M0'
                ' -.3 Q.36 .06 .28 .5 Q.08 .16 0 -.02 Z" class="fill"/>';
        }
        if (i == 5) {
            // uniswap
            return '<path d="M-.7 .7 Q-.74 .06 -.44 -.2 Q-.18 -.46 .14 -.5 Q.5 -.53 .62 -.28 Q.73 -.03 .5 .0'
                '7 L.44 .3 Q.34 .58 .1 .7 Z" class="fill"/><path d="M.1 -.52 L.3 -1.02 L.45 -.46 Z" class'
                '="fill"/><path d="M-.52 -.16 Q-.8 0 -.88 .34 M-.46 .08 Q-.76 .24 -.82 .58" class="st" st'
                'roke-width=".08"/><circle cx=".24" cy="-.18" r=".12" class="paperfill"/><path d="M.5 -.0'
                '4 h.12" class="paperst" stroke-width=".07"/>';
        }
        if (i == 6) {
            // opensea
            return '<circle r=".74" class="fill"/><path d="M-.06 -.54 V.18" class="paperst" stroke-width=".0'
                '8"/><path d="M-.02 -.5 Q.46 -.1 .04 .16 Z" class="paperfill"/><path d="M-.1 -.28 Q-.46 -'
                '.02 -.12 .16 Z" class="paperfill"/><path d="M-.5 .32 H.5 M-.38 .5 H.38" class="paperst" '
                'stroke-width=".08"/>';
        }
        if (i == 7) {
            // binance
            return '<path d="M0 -.26 L.26 0 L0 .26 L-.26 0 Z" class="fill"/><path d="M0 -.72 L.2 -.52 L0 -.3'
                '2 L-.2 -.52 Z" class="fill"/><path d="M0 .32 L.2 .52 L0 .72 L-.2 .52 Z" class="fill"/><p'
                'ath d="M.52 -.2 L.72 0 L.52 .2 L.32 0 Z" class="fill"/><path d="M-.52 -.2 L-.32 0 L-.52 '
                '.2 L-.72 0 Z" class="fill"/>';
        }
        revert BadIndex();
    }
}
