// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

/// @title UnderwaterNames
/// @notice The trait names, and the metadata attributes built from them.
///
/// @dev GENERATED by `python art/solidify.py` from art/traits/manifest.json. Do
///      not edit by hand — regenerate.
///
///      Held apart from the art contracts because this covers all ten categories,
///      including the three with nothing drawn: fauna is procedural, pigment and
///      substrate are colour. And because the JSON is assembled here, where the
///      label bytes already are, rather than returning ten strings for the
///      renderer to stitch together.
///
///      Labels are not part of `provenance` — that hash covers the trait table,
///      which is indices. A name can be corrected by deploying a new renderer,
///      right up until `freezeRenderer`.
contract UnderwaterNames {
    error BadIndex();

    /// @notice The token's `attributes` entries for one plate's packed traits.
    /// @dev Every entry carries a trailing comma, because the renderer always
    ///      appends the live ones — depth, state, scars — after these. Ten static
    ///      traits followed by at least one dynamic one, so the comma is never
    ///      dangling.
    function attributes(uint256 traits) external pure returns (string memory) {
        return string.concat(_first(traits), _rest(traits));
    }

    /// @dev Diver, Headgear, Held, Relic, Emblem.
    function _first(uint256 traits) private pure returns (string memory) {
        return string.concat(
            _attr("Diver", _diver(traits & 15)),
            _attr("Headgear", _headgear((traits >> 4) & 15)),
            _attr("Held", _held((traits >> 8) & 15)),
            _attr("Relic", _relic((traits >> 12) & 15)),
            _attr("Emblem", _emblem((traits >> 16) & 15))
        );
    }

    /// @dev Scene, Tether, Fauna, Pigment, Substrate.
    function _rest(uint256 traits) private pure returns (string memory) {
        return string.concat(
            _attr("Scene", _scene((traits >> 20) & 15)),
            _attr("Tether", _tether((traits >> 24) & 15)),
            _attr("Fauna", _fauna((traits >> 28) & 15)),
            _attr("Pigment", _pigment((traits >> 32) & 15)),
            _attr("Substrate", _substrate((traits >> 36) & 15))
        );
    }

    /// @dev One attribute object. Factored out so the JSON punctuation is stored
    ///      once instead of ten times.
    function _attr(string memory kind, string memory value) private pure returns (string memory) {
        return string.concat('{"trait_type":"', kind, '","value":"', value, '"},');
    }

    /// @dev Diver, 6 options. Reverts rather than
    ///      returning a placeholder, so a bad index cannot mint quiet metadata.
    function _diver(uint256 i) private pure returns (string memory) {
        if (i == 0) return "Diver";
        if (i == 1) return "Skeleton";
        if (i == 2) return "Cephalopod";
        if (i == 3) return "Jellyfish";
        if (i == 4) return "Anglerfish";
        if (i == 5) return "Salvage drone";
        revert BadIndex();
    }

    /// @dev Headgear, 5 options. Reverts rather than
    ///      returning a placeholder, so a bad index cannot mint quiet metadata.
    function _headgear(uint256 i) private pure returns (string memory) {
        if (i == 0) return "Brass hardhat";
        if (i == 1) return "Scuba mask";
        if (i == 2) return "Pressure sphere";
        if (i == 3) return "Bare";
        if (i == 4) return "Salvage rig";
        revert BadIndex();
    }

    /// @dev Held, 6 options. Reverts rather than
    ///      returning a placeholder, so a bad index cannot mint quiet metadata.
    function _held(uint256 i) private pure returns (string memory) {
        if (i == 0) return "Harpoon";
        if (i == 1) return "Lantern";
        if (i == 2) return "Salvage bag";
        if (i == 3) return "Dive slate";
        if (i == 4) return "Cut hose";
        if (i == 5) return "Empty hands";
        revert BadIndex();
    }

    /// @dev Relic, 15 options. Reverts rather than
    ///      returning a placeholder, so a bad index cannot mint quiet metadata.
    function _relic(uint256 i) private pure returns (string memory) {
        if (i == 0) return "None";
        if (i == 1) return "Quill";
        if (i == 2) return "Tulip";
        if (i == 3) return "Hourglass";
        if (i == 4) return "Ingots";
        if (i == 5) return "Ink sac";
        if (i == 6) return "Pepe";
        if (i == 7) return "Doge";
        if (i == 8) return "ZachXBT";
        if (i == 9) return "Saylor";
        if (i == 10) return "Dead coin";
        if (i == 11) return "Barnacled coin";
        if (i == 12) return "Cut crystal";
        if (i == 13) return "Unicorn figurehead";
        if (i == 14) return "Satoshi";
        revert BadIndex();
    }

    /// @dev Emblem, 8 options. Reverts rather than
    ///      returning a placeholder, so a bad index cannot mint quiet metadata.
    function _emblem(uint256 i) private pure returns (string memory) {
        if (i == 0) return "Unstamped";
        if (i == 1) return "Bitcoin";
        if (i == 2) return "Ethereum";
        if (i == 3) return unicode"Ink · Kraken";
        if (i == 4) return "Robinhood";
        if (i == 5) return "Uniswap";
        if (i == 6) return "OpenSea";
        if (i == 7) return "Binance";
        revert BadIndex();
    }

    /// @dev Scene, 5 options. Reverts rather than
    ///      returning a placeholder, so a bad index cannot mint quiet metadata.
    function _scene(uint256 i) private pure returns (string memory) {
        if (i == 0) return "Open water";
        if (i == 1) return "Wreck";
        if (i == 2) return "Kelp";
        if (i == 3) return "Thermal vent";
        if (i == 4) return "Chain curtain";
        revert BadIndex();
    }

    /// @dev Tether, 4 options. Reverts rather than
    ///      returning a placeholder, so a bad index cannot mint quiet metadata.
    function _tether(uint256 i) private pure returns (string memory) {
        if (i == 0) return "Intact rope";
        if (i == 1) return "Frayed";
        if (i == 2) return "Severed";
        if (i == 3) return "Anchor chain";
        revert BadIndex();
    }

    /// @dev Fauna, 4 options. Reverts rather than
    ///      returning a placeholder, so a bad index cannot mint quiet metadata.
    function _fauna(uint256 i) private pure returns (string memory) {
        if (i == 0) return "Shoal";
        if (i == 1) return "Lone predator";
        if (i == 2) return "Motes";
        if (i == 3) return "Nothing";
        revert BadIndex();
    }

    /// @dev Pigment, 5 options. Reverts rather than
    ///      returning a placeholder, so a bad index cannot mint quiet metadata.
    function _pigment(uint256 i) private pure returns (string memory) {
        if (i == 0) return "Sumi black";
        if (i == 1) return "Sepia";
        if (i == 2) return "Indigo";
        if (i == 3) return "Oxblood";
        if (i == 4) return "Gold leaf";
        revert BadIndex();
    }

    /// @dev Substrate, 4 options. Reverts rather than
    ///      returning a placeholder, so a bad index cannot mint quiet metadata.
    function _substrate(uint256 i) private pure returns (string memory) {
        if (i == 0) return "Washi";
        if (i == 1) return "Vellum";
        if (i == 2) return "Ledger paper";
        if (i == 3) return "Blueprint";
        revert BadIndex();
    }
}
